# Generated by Django 3.2 on 2022-06-18 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='booklist',
            name='deleted_flag',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='BookListLog',
        ),
    ]
